"""
Regenerate the `source.type == "numpy_port"` entries of
`canonical_combinations.json` from the v0.1 numpy Toure reference.

The JSON file is the single source of truth consumed by the G2
equivalence check (`phase1b/implementation_gate/equivalence_check.py`,
to be written in session D). It contains three categories of entries:

  1. `source.type == "numpy_port"` — regenerated by this script from
     `reference_toure.py`. Over-writes without warning.
  2. `source.type == "toure_1994_tableN"` / `"mcdonald_1990_tableN"` —
     transcribed from published papers in session D. **Never modified
     by this script** — they are hand-edited and reviewed. The script
     preserves them verbatim on re-run.
  3. `source.type == "manual"` — ad-hoc combinations added for
     debugging. Preserved, but they are not expected to stay in the
     file past session E.

Grid choice for the first (session B) numpy-port set:
  - s_cm ∈ {1, 3, 5} — SPEC §5 learnable range endpoints and midpoint.
  - m_v ∈ {0.25, 0.55, 0.83} — Moor House observed envelope (G3
    observational-envelope report) endpoints and midpoint.
  - N_l_per_m3 ∈ {10³, 10⁴, 10⁵} — SPEC §5 learnable range, covering
    the sparse / midpoint / dense canopy regimes. Exercising all three
    is important for the G2 gate because the v0.1 Rayleigh reference
    is optically thick at N_l = 10⁴ (σ° saturates to the crown-direct
    ceiling and ground contributions drop below the numerical floor);
    at N_l = 10³ the canopy is thin enough that ground parameters
    (m_v, s) propagate into σ°, which is the regime where the gate
    meaningfully tests ground-side physics.
  - Other parameters: SPEC §5 fixed values (crown geometry) and
    learnable-range midpoints (N_b = 10³, σ_orient = 30°, m_g = 0.45).
    θ_inc = 41.5° (Moor House mean descending-orbit IW).

Usage:
    python phase1b/physics/reference_mimics/generate_numpy_port_combinations.py
"""

from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

# Run-as-script support.
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from phase1b.physics.reference_mimics.reference_toure import (  # noqa: E402
    MimicsToureParams,
    mimics_toure_single_crown,
)

CANONICAL_JSON = (
    Path(__file__).resolve().parent / "canonical_combinations.json"
)

# ─── Grid definition ────────────────────────────────────────────────────────

# SPEC §5 / SPEC §7 learnable surface RMS height range — endpoints + midpoint.
S_GRID_CM = [1.0, 3.0, 5.0]
# Moor House observational-envelope m_v range (G3 report) — endpoints + midpoint.
M_V_GRID = [0.25, 0.55, 0.83]
# SPEC §5 leaf density learnable range — endpoints + midpoint (log-scale).
N_L_GRID_PER_M3 = [1.0e3, 1.0e4, 1.0e5]

# SPEC §5 fixed crown geometry.
H_C_M = 0.4
A_B_CM = 0.2   # branch radius 2 mm
L_B_CM = 8.0   # branch half-length 8 cm
A_L_CM = 1.0   # leaf disc radius 1 cm
T_L_CM = 0.03  # leaf disc thickness 0.3 mm

# SPEC §5 learnable-range midpoints (priors withdrawn, init at mean).
N_B_PER_M3 = 1.0e3       # geometric mean of [10², 10⁴]
SIGMA_ORIENT_DEG = 30.0  # midpoint of [15, 60] degrees
M_G = 0.45               # midpoint of [0.3, 0.6] g/g per DEV-1b-002

# SPEC §5 fixed / sensor.
L_CORR_CM = 5.0
THETA_INC_DEG = 41.5
FREQ_HZ = 5.405e9

# Dielectric name kept in each entry so the equivalence check knows
# which ground model to use when the PyTorch MIMICS is called.
GROUND_DIELECTRIC = "mironov"


def _source_code_hash() -> str:
    """SHA-256 of reference_toure.py — record which code produced each σ°."""
    src = (
        Path(__file__).resolve().parent / "reference_toure.py"
    ).read_text(encoding="utf-8")
    return hashlib.sha256(src.encode("utf-8")).hexdigest()


def _build_combination(
    s_cm: float, m_v: float, N_l_per_m3: float, code_hash: str
) -> dict:
    params = MimicsToureParams(
        h_c_m=H_C_M,
        a_b_cm=A_B_CM,
        l_b_cm=L_B_CM,
        a_l_cm=A_L_CM,
        t_l_cm=T_L_CM,
        N_b_per_m3=N_B_PER_M3,
        N_l_per_m3=N_l_per_m3,
        sigma_orient_deg=SIGMA_ORIENT_DEG,
        m_g=M_G,
        m_v=m_v,
        s_cm=s_cm,
        l_corr_cm=L_CORR_CM,
        theta_inc_deg=THETA_INC_DEG,
        freq_hz=FREQ_HZ,
    )
    sigma_vv_db, sigma_vh_db = mimics_toure_single_crown(params)
    n_l_exp = int(round(np.log10(N_l_per_m3)))
    return {
        "id": (
            f"numpy_port_s{int(s_cm):d}cm_mv{int(round(m_v * 100)):02d}"
            f"_Nl1e{n_l_exp}"
        ),
        "source": {
            "type": "numpy_port",
            "module": "phase1b.physics.reference_mimics.reference_toure",
            "function": "mimics_toure_single_crown",
            "code_sha256": code_hash,
            "version": "v0.1",
        },
        "parameters": {
            **params.as_dict(),
            "ground_dielectric": GROUND_DIELECTRIC,
        },
        "reference_sigma": {
            "sigma_vv_db": sigma_vv_db,
            "sigma_vh_db": sigma_vh_db,
        },
        "notes": (
            f"Moor House envelope. s = {s_cm:.1f} cm, m_v = {m_v:.2f}, "
            f"N_l = 1e{n_l_exp} m⁻³. v0.1 Rayleigh + sinc² form factor; "
            "see reference_toure.py docstring 'Known limitations (v0.1)'."
        ),
    }


def _build_sparse_probe(
    s_cm: float, m_v: float, code_hash: str
) -> dict:
    """
    Low-density probe combination where the crown is optically thin and
    ground parameters (m_v, s) visibly drive σ°. Uses SPEC §5 lower
    bounds for both branch and leaf density (N_b = 10², N_l = 10³),
    which the v0.1 Rayleigh+sinc² reference keeps at τ² ≳ 0.5 — in
    this regime the ground-direct term is not numerically suppressed
    and the G2 gate meaningfully exercises the Oh / Mironov coupling.
    """
    params = MimicsToureParams(
        h_c_m=H_C_M,
        a_b_cm=A_B_CM,
        l_b_cm=L_B_CM,
        a_l_cm=A_L_CM,
        t_l_cm=T_L_CM,
        N_b_per_m3=1.0e2,        # SPEC §5 lower bound
        N_l_per_m3=1.0e3,        # SPEC §5 lower bound
        sigma_orient_deg=SIGMA_ORIENT_DEG,
        m_g=M_G,
        m_v=m_v,
        s_cm=s_cm,
        l_corr_cm=L_CORR_CM,
        theta_inc_deg=THETA_INC_DEG,
        freq_hz=FREQ_HZ,
    )
    sigma_vv_db, sigma_vh_db = mimics_toure_single_crown(params)
    return {
        "id": (
            f"numpy_port_sparse_s{int(s_cm):d}cm"
            f"_mv{int(round(m_v * 100)):02d}"
        ),
        "source": {
            "type": "numpy_port",
            "module": "phase1b.physics.reference_mimics.reference_toure",
            "function": "mimics_toure_single_crown",
            "code_sha256": code_hash,
            "version": "v0.1",
        },
        "parameters": {
            **params.as_dict(),
            "ground_dielectric": GROUND_DIELECTRIC,
        },
        "reference_sigma": {
            "sigma_vv_db": sigma_vv_db,
            "sigma_vh_db": sigma_vh_db,
        },
        "notes": (
            f"Sparse-canopy probe (N_b = 1e2, N_l = 1e3; SPEC §5 lower "
            f"bounds). s = {s_cm:.1f} cm, m_v = {m_v:.2f}. Regime where "
            "the crown is optically thin (τ² ≳ 0.5) and ground parameters "
            "drive σ° — selected to exercise ground-side physics "
            "agreement in the G2 equivalence check."
        ),
    }


def generate_combinations() -> list[dict]:
    """Build the numpy-port combinations over the session-B grid."""
    code_hash = _source_code_hash()
    dense_grid = [
        _build_combination(s_cm, m_v, N_l, code_hash)
        for s_cm in S_GRID_CM
        for m_v in M_V_GRID
        for N_l in N_L_GRID_PER_M3
    ]
    # Sparse-canopy probe set: vary s and m_v at the low-density corner.
    sparse_probes = [
        _build_sparse_probe(s_cm, m_v, code_hash)
        for s_cm in S_GRID_CM
        for m_v in M_V_GRID
    ]
    return dense_grid + sparse_probes


def _load_existing(path: Path) -> dict:
    """Load current canonical_combinations.json if present, else scaffold."""
    if not path.exists():
        return {
            "schema_version": 1,
            "description": (
                "Canonical (parameters → σ°) tuples for the Phase 1b G2 "
                "implementation gate (SPEC.md §4). Combinations are one of "
                "three source types: 'numpy_port' (regenerated by "
                "generate_numpy_port_combinations.py), 'toure_1994_tableN' / "
                "'mcdonald_1990_tableN' (hand-transcribed in session D), or "
                "'manual' (ad-hoc debugging entries). The G2 gate requires "
                "σ° agreement within the tolerance_db below between the "
                "differentiable PyTorch MIMICS and each reference_sigma."
            ),
            "tolerance_db": 0.5,
            "combinations": [],
            "created_at": None,
            "last_regenerated_at": None,
        }
    return json.loads(path.read_text(encoding="utf-8"))


def write_canonical(path: Path = CANONICAL_JSON) -> dict:
    """Regenerate numpy_port entries, preserving other source types."""
    now = datetime.now(timezone.utc).isoformat()
    existing = _load_existing(path)

    # Preserve non-numpy_port entries verbatim.
    preserved = [
        c for c in existing.get("combinations", [])
        if c.get("source", {}).get("type") != "numpy_port"
    ]

    new_numpy_port = generate_combinations()

    combined = {
        "schema_version": existing.get("schema_version", 1),
        "description": existing.get("description"),
        "tolerance_db": existing.get("tolerance_db", 0.5),
        "created_at": existing.get("created_at") or now,
        "last_regenerated_at": now,
        "combinations": new_numpy_port + preserved,
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(combined, indent=2) + "\n", encoding="utf-8")
    return combined


def main() -> int:
    out = write_canonical()
    n_numpy_port = sum(
        1 for c in out["combinations"]
        if c["source"]["type"] == "numpy_port"
    )
    n_other = len(out["combinations"]) - n_numpy_port
    print(f"Wrote {CANONICAL_JSON}")
    print(f"  numpy_port entries      : {n_numpy_port}")
    print(f"  preserved (other) entries: {n_other}")
    print(f"  tolerance_db            : {out['tolerance_db']}")
    # Brief σ° summary.
    print()
    print("numpy_port σ° summary:")
    for c in out["combinations"]:
        if c["source"]["type"] != "numpy_port":
            continue
        p = c["parameters"]
        r = c["reference_sigma"]
        n_l_exp = int(round(np.log10(p["N_l_per_m3"])))
        print(
            f"  s = {p['s_cm']:.1f}  m_v = {p['m_v']:.2f}  "
            f"N_l = 1e{n_l_exp:d}    "
            f"σ°_VV = {r['sigma_vv_db']:+7.2f}   "
            f"σ°_VH = {r['sigma_vh_db']:+7.2f}  dB"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
